### ISSUE TITLE
Issue with Rigel update

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/atom#6]
Hi @MisterOwlPT !

So, that problem I mentioned in our meeting today with Rigel came back, even after pulling again from the flow branch.

After trying to run that compose job, I get the following error message:

```
WARNING - Press CTRL-C / CTRL-Z to stop execution
Connecting to providers
Created Docker network 'rigel-simulation-6b59b5ee-2252-11ee-8d75-eb3be3b61acc'
Created ROS master 'master-6b59b5ee-2252-11ee-8d75-eb3be3b61acc'
Traceback (most recent call last):
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/bin/rigel", line 6, in <module>
    sys.exit(main())
  File "/home/diogo/rigel/rigel/main.py", line 50, in main
    cli()
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/diogo/rigel/rigel/cli/command.py", line 23, in callback
    f(self, *f_args, **f_kwargs)
  File "/home/diogo/rigel/rigel/cli/run.py", line 25, in job
    orchestrator.run_job(job)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 222, in run_job
    self.execute(execution_plan)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 199, in execute
    stage.execute(
  File "/home/diogo/rigel/rigel/executor.py", line 219, in execute
    job.start()
  File "/home/diogo/rigel/rigel/plugins/core/compose/plugin.py", line 224, in start
    self.bringup_ros_nodes()
  File "/home/diogo/rigel/rigel/plugins/core/compose/plugin.py", line 108, in bringup_ros_nodes
    container = self.run_package_container(test_component, master_ip)
  File "/home/diogo/rigel/rigel/plugins/core/compose/plugin.py", line 140, in run_package_container
    kwargs['volumes'] = self.convert_volumes(kwargs['volumes'])
  File "/home/diogo/rigel/rigel/plugins/core/compose/plugin.py", line 92, in convert_volumes
    result.append(tuple(volume.split(':')))
AttributeError: 'tuple' object has no attribute 'split'

```

If there's anything different I should be doing since the update to this branch, let me know! :smile:

**Comment by MisterOwlPT** [comment]
Hi @Kazadhum 😃 

Can you show me how you are configuring the plugin on your Rigelfile?

**Comment by Kazadhum** [comment]
Hey @MisterOwlPT, there you go! :smile: 

```
compose_rigelfile_test:
    plugin: "rigel.plugins.core.ComposePlugin"
    with:
      timeout: 300.0
      components:
        -
          name: "simapp"
          image: "dvieira2001/atom:latest"

          command: ["/bin/bash", "-c", "source /home/rigeluser/ros_workspace/devel/setup.bash && roslaunch t2rgb_bringup simapp_launch.launch motion_sequence_file:=/home/rigeluser/ros_workspace/src/t2rgb/movement_sequences/movement_sequence.json"]

          envs:
            DISPLAY: "{{ vars.DISPLAY }}"

          volumes:
            - !!python/tuple ["/tmp/.X11-unix", "/tmp/.X11-unix"]

          # devices:
          #   - "/dev/dri:/dev/dri"

        -
          name: "robotapp"
          image: "dvieira2001/atom:latest"  

          command: ["/bin/bash", "-c", "source /home/rigeluser/ros_workspace/devel/setup.bash && roslaunch t2rgb_bringup robotapp_launch.launch output_folder:=/home/rigeluser/ros_workspace/src/t2rgb/datasets/t2rgb overwrite:=true"]

          envs:
            DISPLAY: "{{ vars.DISPLAY }}"
          
          volumes:
            - !!python/tuple ["/tmp/.X11-unix", "/tmp/.X11-unix"]

          # devices:
          #   - "/dev/dri:/dev/dri"
          
          introspection: False
```

**Comment by MisterOwlPT** [comment]
@Kazadhum, it's _now_ fixed **in branch ```develop```**!
Just checkout said branch, `git pull`, and you should be ready to go (no changes required on your side)!

I am preparing a new stable release of Rigel and I'm currently merging everything into a single development branch `develop`. Also, minor new features and bug fixes will from now on be pushed into that branch.

I won't delete the `flow` branch, but I don't see any reason for us both to continue using it...
I also don't think you'll need that much work to update your pipelines 😃

**Comment by Kazadhum** [comment]
Thank you!
